#!/usr/bin/env python3
"""CDLO git bridge — generate a Change payload from a real repository.

Usage:
    python scripts/extract_payload.py --repo /path/to/repo --intent /path/to/intent.md [--commit <sha>]

Reads the latest commit (or a given sha) and the project's intent file, and
emits a GIT-MODE payload ready to paste into the operator. Nothing is invented:
files without a declared ID in the intent file are marked (undeclared), and the
operator scores that as drift per the GIT MODE section of rules.md.

Intent file lines the extractor understands (same shape as TRY_IT.md):
    - Scope paths: products/core/, docs/
    - Assets: API-4410=src/api.py, DOC-2210=docs/build.md, AST-9912
    - Open objectives: OBJ-12: export endpoint
    - Authorized actors: @alice, @bob
Asset entries may be bare IDs or ID=path mappings; only mapped paths can be
matched to commit files.
"""
import argparse
import re
import subprocess
import sys


def sh(args, cwd):
    r = subprocess.run(args, cwd=cwd, capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit(f"git error: {r.stderr.strip()}")
    return r.stdout.strip()


def parse_intent(path):
    text = open(path, encoding="utf-8").read()
    def grab(label):
        m = re.search(rf"{label}\s*:\s*(.+)", text, re.IGNORECASE)
        return [x.strip() for x in m.group(1).split(",")] if m else []
    scope = []
    for sp in grab("Scope paths"):
        sp = sp.strip()
        scope.append("" if sp in (".", "/", "./") else sp.rstrip("/") + "/")  # "" matches repo root (everything)
    assets, asset_map = [], {}
    for a in grab("Assets"):
        if "=" in a:
            aid, ap = a.split("=", 1)
            assets.append(aid.strip())
            asset_map[ap.strip()] = aid.strip()
        else:
            assets.append(a.strip())
    return {
        "scope": scope,
        "assets": assets,
        "asset_map": asset_map,
        "actors": grab("Authorized actors"),
        "objectives": grab("Open objectives"),
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", required=True)
    ap.add_argument("--intent", required=True)
    ap.add_argument("--commit", default="HEAD")
    args = ap.parse_args()

    intent = parse_intent(args.intent)
    sha = sh(["git", "rev-parse", "--short", args.commit], args.repo)
    author = sh(["git", "log", "-1", "--format=%an", args.commit], args.repo)
    ts = sh(["git", "log", "-1", "--format=%cI", args.commit], args.repo)
    msg = sh(["git", "log", "-1", "--format=%s", args.commit], args.repo)
    files = [f for f in sh(
        ["git", "show", "--name-only", "--format=", args.commit], args.repo
    ).splitlines() if f.strip()]

    lines = [
        "# GIT-MODE PAYLOAD (generated by scripts/extract_payload.py — see rules.md GIT MODE)",
        "",
        "Change payload:",
        f"commit {sha} | author @{author.replace(' ', '_').lower()} | {ts}",
        f'msg: "{msg}"',
        "files:",
    ]
    for f in files:
        in_scope = any(f.startswith(s) for s in intent["scope"])
        aid = intent["asset_map"].get(f)
        id_part = f"(ID: {aid})" if aid else "(undeclared)"
        scope_part = "" if in_scope else " [out-of-scope]"
        lines.append(f"  {f} sig:@{author.replace(' ', '_').lower()} {id_part}{scope_part}")

    print("\n".join(lines))
    print(
        f"\n# Extractor summary: {len(files)} file(s), "
        f"{sum(1 for f in files if f in intent['asset_map'])} declared, "
        f"{sum(1 for f in files if not any(f.startswith(s) for s in intent['scope']))} out-of-scope. "
        f"Paste the intent file plus the block above into the operator."
    )


if __name__ == "__main__":
    main()
